# Lab 3: Singing a song

---
self-contained: true
title: Lab 3- Singing a song
format:
    html:
        theme: solar
author: Shreya Vanaki
---

In [409]:
# import necessary libraries and packages
import numpy as np
import pandas as pd

# Dataset

In [410]:
xmas = pd.read_csv("https://www.dropbox.com/scl/fi/qxaslqqp5p08i1650rpc4/xmas.csv?rlkey=erdxi7jbh7pqf9fh4lv4cayp5&dl=1")
xmas

    Day Day.in.Words  Gift.Item        Verb Adjective        Location
0     1        first  partridge         NaN       NaN  in a pear tree
1     2       second       dove         NaN    turtle             NaN
2     3        third        hen         NaN    french             NaN
3     4       fourth       bird         NaN   calling             NaN
4     5        fifth       ring         NaN    golden             NaN
5     6        sixth      goose    a-laying       NaN             NaN
6     7      seventh       swan  a-swimming       NaN             NaN
7     8       eighth       maid   a-milking       NaN             NaN
8     9        ninth       lady     dancing       NaN             NaN
9    10        tenth       lord   a-leaping       NaN             NaN
10   11     eleventh      piper      piping       NaN             NaN
11   12      twelfth    drummer    drumming       NaN             NaN

In [411]:
xmas2 = pd.read_csv("https://www.dropbox.com/scl/fi/p9x9k8xwuzs9rhp582vfy/xmas_2.csv?rlkey=kvc3j3lmyn4opcidsrhcmrof1&dl=1")

# Function 1: pluralize_gift()

In [412]:
obj_1 = "foot"
obj_2 = "baby"
obj_3 = "tree"

obj_1.find("oo")
obj_2[-1]
obj_3.find("oo")

obj_1.replace("oo", "ee")
obj_2.replace("y", "ies")
obj_3 + "s"

'trees'

In [413]:
def pluralize_gift(gift):
    """
    Returns plural of a noun
  
    Parameters
    ----------
    gift: str
      A noun
    
    Return
    ------
    str
    Plural version
    """
    if "oo" in gift:
        gift = gift.replace("oo", "ee")
    elif gift.endswith('y'):
        gift = gift[:-1] + 'ies'
    else:
        gift = gift + 's'

    return gift

In [414]:
vectorized_gift = np.vectorize(pluralize_gift)
vectorized_gift

In [415]:
# Should work
pluralize_gift("goose")

# Will work if your function is vectorized! 
#pluralize_gift(xmas['Gift.Item'])

'geese'

# Function 2: make_phrase()

In [416]:
def make_phrase(num, num_word, item, verb, adjective, location):
    """
    This function constructs a phrase based on the given inputs.
    
    Parameters:
    - num (int): The number associated with the item.
    - num_word (str): The word representation of the number.
    - item (str): The main gift item.
    - verb (str): The verb associated with the item, if any.
    - adjective (str): The adjective describing the item, if any.
    - location (str): The location associated with the item, if any.
    
    Returns:
    - str: The constructed phrase.
    """
  
    # Step 1: Replace NAs with blank strings
    if pd.isna(verb):
        verb = ""
    if pd.isna(adjective):
        adjective = ""
    if pd.isna(location):
        location = ""
  
  # Step 2: If the day number is larger than 1, the gift items need pluralized!
  # Hint: call the function you created above!
  
    if num > 1:
        item = pluralize_gift(item)
  # Step 3: Figure out if a gift item starts with a vowel
    starts_with_vowel = item[0].lower() in ['a', 'e', 'i', 'o', 'u']
    num_to_word = {
    1: 'one',
    2: 'two',
    3: 'three',
    4: 'four',
    5: 'five',
    6: 'six',
    7: 'seven',
    8: 'eight',
    9: 'nine',
    10: 'ten',
    11: 'eleven',
    12: 'twelve',
    }
    xmas['Num_Word'] = xmas['Day'].map(num_to_word)
    xmas2['Num_Word'] = xmas['Day'].map(num_to_word)

  # Step 4: For the first day, if the gift item starts with a vowel, replace the day with "an" and if the gift item does not start with a vowel, replace the day with "a" (e.g. a partridge in a pear tree). If it is not the first day, use just the number word (e.g. ten lords a leap)
    if num  == 1:
    
        # For the first day
        if starts_with_vowel:
            num_word = "an"
        else:
            num_word = "a"
    else:
        num_word = num_to_word.get(num)
  # Step 5: Put all of the pieces together into one string and return!
    
    phrase = f"{num_word} {adjective} {item} {verb} {location}"
    phrase = ' '.join(phrase.split())
    return phrase

# Test Your Function

In [417]:
make_phrase(num=1, num_word="one", item="apple", verb="flew", adjective='white', location='in a pear tree')

'an white apple flew in a pear tree'

In [418]:
#use the lambda  function to iterate  through each column
xmas["Full.Phrase"] = xmas.apply(lambda x: make_phrase(x["Day"], 
                                                       x["Num_Word"], 
                                                       x["Gift.Item"], 
                                                       x["Verb"], 
                                                       x["Adjective"],
                                                       x["Location"]),axis=1)

In [419]:
#use the lambda  function to iterate  through each column
xmas2["Full.Phrase"] = xmas2.apply(lambda x: make_phrase(x["Day"], 
                                                       x["Num_Word"], 
                                                       x["Gift.Item"], 
                                                       x["Verb"], 
                                                       x["Adjective"],
                                                       x["Location"]),axis=1)

In [420]:
xmas

,Day,Day.in.Words,Gift.Item,Verb,Adjective,Location,Num_Word,Full.Phrase
0,1,first,partridge,NaN,NaN,in a pear tree,one,a partridge in a pear tree
1,2,second,dove,NaN,turtle,NaN,two,two turtle doves
2,3,third,hen,NaN,french,NaN,three,three french hens
3,4,fourth,bird,NaN,calling,NaN,four,four calling birds
4,5,fifth,ring,NaN,golden,NaN,five,five golden rings
5,6,sixth,goose,a-laying,NaN,NaN,six,six geese a-laying
6,7,seventh,swan,a-swimming,NaN,NaN,seven,seven swans a-swimming
7,8,eighth,maid,a-milking,NaN,NaN,eight,eight maids a-milking
8,9,ninth,lady,dancing,NaN,NaN,nine,nine ladies dancing
9,10,tenth,lord,a-leaping,NaN,NaN,ten,ten lords a-leaping
10,11,eleventh,piper,piping,NaN,NaN,eleven,eleven pipers piping
11,12,twelfth,drummer,drumming,NaN,NaN,twelve,twelve drummers drumming

In [421]:
xmas2

,Day,Day.in.Words,Gift.Item,Verb,Adjective,Location,Num_Word,Full.Phrase
0,1,first,email,NaN,NaN,from Cal Poly,one,an email from Cal Poly
1,2,second,point,NaN,meal,NaN,two,two meal points
2,3,third,pen,NaN,lost,NaN,three,three lost pens
3,4,fourth,review,NaN,course,NaN,four,four course reviews
4,5,fifth,exam,NaN,practice,NaN,five,five practice exams
5,6,sixth,grader,grading,NaN,NaN,six,six graders grading
6,7,seventh,senior,stressing,NaN,NaN,seven,seven seniors stressing
7,8,eighth,mom,a-calling,NaN,NaN,eight,eight moms a-calling
8,9,ninth,party,bumping,NaN,NaN,nine,nine parties bumping
9,10,tenth,load,of laundry,NaN,NaN,ten,ten loads of laundry
10,11,eleventh,friend,goodbye-ing,NaN,NaN,eleven,eleven friends goodbye-ing
11,12,twelfth,hour,sleeping,NaN,NaN,twelve,twelve hours sleeping

# Function 3: sing_day()

In [422]:
def sing_day(dataset, num, phrase_col):
    """
    This function sings the '12 Days of Christmas' song for a specified day, 
    using the given dataset and phrase column. It ensures that the song's lines 
    are grammatically correct with proper use of commas, "and", and periods.
    
    Parameters:
    - dataset (pd.DataFrame): The dataset containing song phrases and day info.
    - num (int): The day number (e.g., 1 for the first day).
    - phrase_col (str): The name of the column in the dataset containing the phrases for each day.
    
    Returns:
    - str: The song for the specified day, with each gift on its own line and grammatically correct punctuation.
    """
    
    # Setup the intro line
    num_word = dataset['Day.in.Words'].iloc[num-1]
    intro = f"On the {num_word} day of Christmas, my true love gave to me:"
    
    # Extract the gift phrases
    gifts = dataset[phrase_col].iloc[:num].tolist()
    
    # Adjust for 'and' and add commas at the end of each gift except for the last one
    if num > 1:
        gifts[0] = "and " + gifts[0]
    
    # Combine the gifts in reverse order
    song_gifts = ",\n".join(gifts[::-1])
    
    # Combine intro and gifts and add a period at the end
    song = f"{intro}\n{song_gifts}."
    
    return song

# Test your function

In [423]:
print(sing_day(xmas, 3, "Full.Phrase"))

On the third day of Christmas, my true love gave to me:
three french hens,
two turtle doves,
and a partridge in a pear tree.

# Use Your Functions!

Note: xmas2 dataset was imported above.

In [424]:
#testing the xmas2 song
print(sing_day(xmas2, 3, "Full.Phrase"))

On the third day of Christmas, my true love gave to me:
three lost pens,
two meal points,
and an email from Cal Poly.

In [425]:
#Printing the entire xmas song
print('\n\n'.join(map(lambda day: sing_day(xmas, day, 'Full.Phrase'), range(1,13))))

On the first day of Christmas, my true love gave to me:
a partridge in a pear tree.

On the second day of Christmas, my true love gave to me:
two turtle doves,
and a partridge in a pear tree.

On the third day of Christmas, my true love gave to me:
three french hens,
two turtle doves,
and a partridge in a pear tree.

On the fourth day of Christmas, my true love gave to me:
four calling birds,
three french hens,
two turtle doves,
and a partridge in a pear tree.

On the fifth day of Christmas, my true love gave to me:
five golden rings,
four calling birds,
three french hens,
two turtle doves,
and a partridge in a pear tree.

On the sixth day of Christmas, my true love gave to me:
six geese a-laying,
five golden rings,
four calling birds,
three french hens,
two turtle doves,
and a partridge in a pear tree.

On the seventh day of Christmas, my true love gave to me:
seven swans a-swimming,
six geese a-laying,
five golden rings,
four calling birds,
three french hens,
two turtle doves,
and a partridge in a pear tree.

On the eighth day of Christmas, my true love gave to me:
eight maids a-milking,
seven swans a-swimming,
six geese a-laying,
five golden rings,
four calling birds,
three french hens,
two turtle doves,
and a partridge in a pear tree.

On the ninth day of Christmas, my true love gave to me:
nine ladies dancing,
eight maids a-milking,
seven swans a-swimming,
six geese a-laying,
five golden rings,
four calling birds,
three french hens,
two turtle doves,
and a partridge in a pear tree.

On the tenth day of Christmas, my true love gave to me:
ten lords a-leaping,
nine ladies dancing,
eight maids a-milking,
seven swans a-swimming,
six geese a-laying,
five golden rings,
four calling birds,
three french hens,
two turtle doves,
and a partridge in a pear tree.

On the eleventh day of Christmas, my true love gave to me:
eleven pipers piping,
ten lords a-leaping,
nine ladies dancing,
eight maids a-milking,
seven swans a-swimming,
six geese a-laying,
five golden rings,
four calling birds,
three french hens,
two turtle doves,
and a partridge in a pear tree.

On the twelfth day of Christmas, my true love gave to me:
twelve drummers drumming,
eleven pipers piping,
ten lords a-leaping,
nine ladies dancing,
eight maids a-milking,
seven swans a-swimming,
six geese a-laying,
five golden rings,
four calling birds,
three french hens,
two turtle doves,
and a partridge in a pear tree.

# Printing the xmas2 song

In [426]:
print('\n\n'.join(map(lambda day: sing_day(xmas2, day, 'Full.Phrase'), range(1,13))))

On the first day of Christmas, my true love gave to me:
an email from Cal Poly.

On the second day of Christmas, my true love gave to me:
two meal points,
and an email from Cal Poly.

On the third day of Christmas, my true love gave to me:
three lost pens,
two meal points,
and an email from Cal Poly.

On the fourth day of Christmas, my true love gave to me:
four course reviews,
three lost pens,
two meal points,
and an email from Cal Poly.

On the fifth day of Christmas, my true love gave to me:
five practice exams,
four course reviews,
three lost pens,
two meal points,
and an email from Cal Poly.

On the sixth day of Christmas, my true love gave to me:
six graders grading,
five practice exams,
four course reviews,
three lost pens,
two meal points,
and an email from Cal Poly.

On the seventh day of Christmas, my true love gave to me:
seven seniors stressing,
six graders grading,
five practice exams,
four course reviews,
three lost pens,
two meal points,
and an email from Cal Poly.

On the eighth day of Christmas, my true love gave to me:
eight moms a-calling,
seven seniors stressing,
six graders grading,
five practice exams,
four course reviews,
three lost pens,
two meal points,
and an email from Cal Poly.

On the ninth day of Christmas, my true love gave to me:
nine parties bumping,
eight moms a-calling,
seven seniors stressing,
six graders grading,
five practice exams,
four course reviews,
three lost pens,
two meal points,
and an email from Cal Poly.

On the tenth day of Christmas, my true love gave to me:
ten loads of laundry,
nine parties bumping,
eight moms a-calling,
seven seniors stressing,
six graders grading,
five practice exams,
four course reviews,
three lost pens,
two meal points,
and an email from Cal Poly.

On the eleventh day of Christmas, my true love gave to me:
eleven friends goodbye-ing,
ten loads of laundry,
nine parties bumping,
eight moms a-calling,
seven seniors stressing,
six graders grading,
five practice exams,
four course reviews,
three lost pens,
two meal points,
and an email from Cal Poly.

On the twelfth day of Christmas, my true love gave to me:
twelve hours sleeping,
eleven friends goodbye-ing,
ten loads of laundry,
nine parties bumping,
eight moms a-calling,
seven seniors stressing,
six graders grading,
five practice exams,
four course reviews,
three lost pens,
two meal points,
and an email from Cal Poly.